### ISSUE TITLE
Players got teleported even if they aren't participating

### ISSUE THREAD

**Issue by Tomut0** [RoinujNosde/TitansBattle#107]
My players got teleported. 
```
  type: FreeForAllGame
```
I'm supposing, it's because they're located in `watchroom` before starting the game. 🤔

**Comment by RoinujNosde** [comment]
Teleported to the spectators room?

**Comment by Tomut0** [comment]
> Teleported to the spectators room?

Nope, to the arena enterances.

**Comment by Tomut0** [comment]
> Did those players join and then leave the game?

No, they aren't.

**Comment by RoinujNosde** [comment]
Any ideas on how to reproduce it?

**Comment by Tomut0** [comment]
https://github.com/RoinujNosde/TitansBattle/blob/master/src/main/java/me/roinujnosde/titansbattle/BaseGame.java#L550

Look at this boy, teleporting each warrior of the group 👺 👍🏻

**Comment by RoinujNosde** [comment]
Let's not git blame that
