### ISSUE TITLE
Cant set Arena Entrance?

### ISSUE THREAD

**Issue by TomLewis** [RoinujNosde/TitansBattle#117]
Hi! 
First time trying to setup TitansBattle, but having a bit of an issue with trying to set an arena, The docs seem to be dated and dont give much information, I have got as far as trying to setup destinations, but the auto-tab for the Arena Entrance isnt working.
Just says "Error: please specify one of (exit, lobby, border_center, watchroom)

`/tb game setdestination crewbattle1 ARENA_ENTRANCE`

So I cant get an arena built.

If I try to start a game it, ti says "Im sorry but there was an error performing this command" there is then console errors and a console message to set all destinations. 

Second question is, what is border_center?

**Comment by RoinujNosde** [comment]
Hi,
The arena_entrance requires a number, I should fix that message.
`/tb game setdestination crewbattle1 ARENA_ENTRANCE <entrance number>`
It's possible to set unlimited entrances, each player/clan should be teleported to one.

`border_center` enables a World border around the arena, you should probably use it in a separate world.

**Comment by TomLewis** [comment]
Ahhhh that makes more sense now! Could just be as simple as a feedback message in chat saying you need to add a number!

Can I also suggest when you first create an arena a message is out in chat with a list of the things you need to do to create a working arena, I'm just kind of trying to figure out all out myself!

Can I create an arena without a border? I planned to use some worldguard claims as fight regions in my survival, if so how would I remove one I set, I've been doing this on a test server for now!

**Comment by RoinujNosde** [comment]
> Can I create an arena without a border? I planned to use some worldguard claims as fight regions in my survival, if so how would I remove one I set, I've been doing this on a test server for now!

Sure, although I recommend building a wall or something surrounding the area, so participants don't run away or hide.
Set `world_border.enable: false` to disable it.
