### ISSUE TITLE
Spam de erro no console na versão 1.20.4 [purpur]

### ISSUE THREAD

**Issue by Yurkhun** [RoinujNosde/TitansBattle#126]
![image](https://github.com/RoinujNosde/TitansBattle/assets/95500637/792b236c-c743-4f97-a3ad-02d5a2798614)

Olá, o titansbattle do nada começa a flodar o console com essa msg repetida varias vezes, tenho conhecimento que ele foi feito ate a 1.19, mas existiria uma solução para isso?

**Comment by SrBedrock** [comment]
@Yurkhun teste essa versão: https://ci.roinujnosde.me/job/TitansBattle/191/
