### ISSUE TITLE
Itens de Netherita não estão sendo reconhecidos

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#16]
Itens de netherita não estão sendo reconhecidos ao entrar em eventos onde o inventário precisa estar limpo.

**Comment by RoinujNosde** [comment]
Qualquer item desse tipo?

**Comment by SrBedrock** [comment]
Qualquer item de netherita, seja armadura ou ferramentas, equipadas ou no inventário.
