### ISSUE TITLE
Modo de Desafio

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#2]
### Desafio entre grupos

O líder do clã ou facção desafia outros clãs ou facções, caso o líder desafiado aceite a guerra, todos os membros dos dois grupos precisam entrar para a guerra dentro de um tempo definido;

Sugestão de nome para o tipo de evento:
- Itens dos próprios jogadores;
- Itens definidos pelo servidor.

#### Comandos

- `/tb challenge [tag] [arena]` - Desafiar outro clã ou facção.
- `/tb accept` ou `/tb challenge accept` - Aceitar um desafio.
- `/tb deny` ou `/tb challenge deny` - Negar um desafio.

Caso uma arena não seja especificada, escolher uma aleatória disponível?

***

### Desafio entre jogadores

Jogadores desafiam uns aos outros para batalhar até a morte!

Sugestão de nome para o tipo de evento:
- Itens dos próprios jogadores;
- Itens definidos pelo servidor.

#### ~~Comandos~~

- `/tb challenge [jogador] [arena]` - Desafiar outro clã ou facção.
- `/tb accept` ou `/tb challenge accept` - Aceitar um desafio.
- `/tb deny` ou `/tb challenge deny` - Negar um desafio.

Caso uma arena não seja especificada, escolher uma aleatória disponível?

**Comment by SrBedrock** [comment]
## Adicionar um sistema de desafio entre dois grupos. (clãs ou facções)

~~Seria ideal ter sugestão de sub-comandos sugerido em #9 antes da adição deste sistema.~~
**[Edit]** Implementado nas ultimas versões do plugin.


### Desafio entre grupos

O líder do clã ou facção desafia outros clãs ou facções, caso o líder desafiado aceite a guerra, todos os membros dos dois grupos precisam entrar para a guerra dentro de um tempo definido;

~~Sugestão de nome para o tipo de evento:~~
- ~~Itens dos próprios jogadores: GROUPS_CHALLENGE_REAL~~
- ~~Itens definidos pelo servidor: GROUPS_CHALLENGE_FUN~~
**[Edit]** Sistema de modo de jogo alterado nas ultimas versões.

#### Comandos

- `/tb challenge [nome] [tag/facção]` - Desafiar outro clã ou facção.
- `/tb accept` ou `/tb challenge accept` - Aceitar um desafio.
- `/tb deny` ou `/tb challenge deny` - Negar um desafio.

***

### ~~Desafio entre jogadores~~

~~Jogadores desafiam uns aos outros para batalhar até a morte!~~

~~Sugestão de nome para o tipo de evento:~~
- ~~Itens dos próprios jogadores: FREEFORALL_CHALLENGE_REAL~~
- ~~Itens definidos pelo servidor: FREEFORALL_CHALLENGE_FUN~~

#### ~~Comandos~~

- ~~`/tb challenge [nome] [player]` - Desafiar outro clã ou facção.~~
- ~~`/tb accept` ou `/tb challenge accept` - Aceitar um desafio.~~
- ~~`/tb deny` ou `/tb challenge deny` - Negar um desafio.~~

**[Edit]** Acho que isso fugiria muito do objetivo do plugin.

**Comment by RoinujNosde** [comment]
Mais alguma mecânica?

Eu tinha feito essas anotações:
Características:
- kits
- 2 pontos de entrada
- camarote
- local de saída
- grupo ou individual
- máximo de players na arena
- mínimo de players na arena
- comando para ver informações da arena (nome, mínimo, máximo, etc) - útil para saber qual arena escolher para o desafio
- estatísticas: kills e mortes em modo de grupo/individual, vitórias em modo de grupo
- comandos para desafiar grupo e player
- dinheiro envolvido?
- qualquer um aceita e é teleportado para a arena
- tempo para aceitar
- tempo para iniciar


Para esse modo de desafio, as configs ficariam numa pasta "arenas" (separada dos games).
Internamente seriam chamadas de ArenaConfiguration.

**Comment by RoinujNosde** [comment]
> Caso uma arena não seja especificada, escolher uma aleatória disponível?

O TAB poderia mostrar apenas as disponíveis.

**Comment by RoinujNosde** [comment]
#58
