### ISSUE TITLE
Remover jogadores expulsos do clã durante evento GROUPS

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#20]
Jogadores expulsos durante a guerra continuam no evento sem clã.
Isso faz com que ele não seja contabilizado como morto pelo clã que ele entrou.
Temos algumas soluções para o problema:
1. Remover o jogador do evento com uma mensagem explicando o motivo;
2. Não permitir a remoção do jogador até o evento acabar.

Acredito que a primeira opção é a melhor.

**Comment by RoinujNosde** [comment]
Expulsos do Clã?

**Comment by SrBedrock** [comment]
> ~Expulsos do Clã?~ Não vi o título.
> 
> Talvez criar uma lista de comandos que não podem ser usados por ninguém (até quem está fora) durante o evento.

Me parece ser uma opção melhor, evita reclamações de jogadores expulsos do clã durante a guerra.
