### ISSUE TITLE
Modo Arqueiro

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#29]
Adicionar uma forma para habilitar o dano apenas da Flecha para que seja possível realizar um evento arqueiro.

**Comment by RoinujNosde** [comment]
Para isso eu estava pensando em ter uma whitelist/blacklist nos itens que pode trazer pro evento.

**Comment by SrBedrock** [comment]
Acho que essa adição seria excelente, principalmente a parte da blacklist onde poderíamos adicionar alguns itens "OP" como por exemplo totem ou maçã dourada dependendo do evento que queremos criar.

Porém, jogadores tendem a dar socos quando estão próximos uns dos outros, destruindo o evento que deveria usar apenas o Arco.

No meu caso o evento seria com itens definidos, se o dano do soco for cancelado já ajuda porque o jogador teria em seu inventário apenas o Arco e flecha.
