### ISSUE TITLE
Adicionar sugestão do comando help traduzido e descrição dos comandos

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#36]
Sub-comando help traduzido para ajuda mas não é realizada a mudança na sugestão ou página de ajuda 
![image](https://user-images.githubusercontent.com/51332006/116319529-0cafb080-a78d-11eb-9fd0-f06bb82d936d.png)

Página de ajuda não possui descrição dos comandos
![image](https://user-images.githubusercontent.com/51332006/116319470-f6095980-a78c-11eb-98a6-de9a7ed2a8b3.png)

**Comment by RoinujNosde** [comment]
67a3f9406578640b990734481e1da26c6049eaaf
