### ISSUE TITLE
Adicionar mensagem para explicar cada evento

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#68]
Adicionar uma mensagem de explicação do evento, será enviada quando o jogador entrar no evento com `/batalha entrar`.

Exemplo:

![image](https://user-images.githubusercontent.com/51332006/173174144-80cc72fd-728d-4884-81c8-b309302d878a.png)

**Comment by RoinujNosde** [comment]
Boa ideia. 

"> Objetivo do jogo:
Mate todos os inimigos para vencer.
"

O que acha dessa mensagem padrão?

**Comment by SrBedrock** [comment]
> Boa ideia.
> 
> "> Objetivo do jogo: Mate todos os inimigos para vencer. "
> 
> O que acha dessa mensagem padrão?

Ótima!
