### ISSUE TITLE
Desabilitar fogo amigo em GROPS_REAL e GROUPS_FUN

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#8]
### Sugestão

Adicionar opção para desabilitar fogo amigo entre membros do próprio clã ou facção durante os eventos.

### Motivo

Em eventos com muitos jogadores é quase impossível não acertar membros do próprio clã.
Existe uma habilidade do mcMMO que dá dano em área e sempre acaba atingindo os membros do próprio clã.

**Comment by SrBedrock** [comment]
Ou ser criado um Addon como o CrakShot-SimpleClans.

https://www.spigotmc.org/resources/crackshot-simpleclans.48339/

**Comment by RoinujNosde** [comment]
@SrBedrock o bug ocorre então com o mcMMO? Qual seria a habilidade que causa isso?

**Comment by SrBedrock** [comment]
@RoinujNosde após algumas atualizações do SimpleClans os membros do próprio clã não conseguem atacar uns aos outros como esperado.

**Comment by SrBedrock** [comment]
> o bug ocorre então com o mcMMO? Qual seria a habilidade que causa isso?
Qualquer habilidade ativa ou passiva do mcMMO não funciona entre aliados, não faço ideia do motivo.
Exemplo de habilidades do machado: https://github.com/mcMMO-Dev/mcMMO/blob/ab276ffe33d916d135642053740a1ff4de769021/src/main/resources/advanced.yml#L169
Exemplo de habilidades da espada: https://github.com/mcMMO-Dev/mcMMO/blob/ab276ffe33d916d135642053740a1ff4de769021/src/main/resources/advanced.yml#L455

**Comment by RoinujNosde** [comment]
> @RoinujNosde após algumas atualizações do SimpleClans, membros do próprio clã não conseguem atacar uns aos outros.

Então está resolvido?

**Comment by SrBedrock** [comment]
Sim, resolvido!
