### ISSUE TITLE
Possibility to have as much arena enterance as it can

### ISSUE THREAD

**Issue by Tomut0** [RoinujNosde/TitansBattle#97]
Currently, we can set only 2 entrance.
What would be if there are 3 groups fighting? All groups teleported to the first entrance.
And it's a little bit disappointing. 😞

**Comment by RoinujNosde** [comment]
Entrances are saved in a map where the key is a number; it wouldn't be difficult to increase the number of entrances.

**Comment by Tomut0** [comment]
> Entrances are saved in a map where the key is a number; it wouldn't be difficult to increase the number of entrances.

Cool 👍🏻
